FROM continuumio/miniconda3

RUN apt-get update && \
    apt upgrade -y && \
    apt -y install build-essential

RUN conda update -yq -n base -c defaults conda

RUN cd / && \
    git clone https://github.com/pywash/pywash.git

RUN conda install -yq python=3.6
RUN cd /pywash && \
    pip3 install -r requirements.txt
    
RUN pip3 install pyod==0.7.6 fancyimpute==0.5.5 psutil

WORKDIR /pywash

CMD ["flask", "run", "--host=0.0.0.0"]